name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # permissions: # Job-level permissions configuration starts here
    #   contents: write # 'write' access to repository contents
    #   pull-requests: write # 'write' access to pull requests
    #   actions: write # 'write' access to workflow runs
    # # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: npm ci, build and test
        run: |
          npm ci
          npm run build --if-present
          npm run test
      # Generate version
      - name: Set env
        run: |
          npm i -g semver
          echo "GITHUB_VERSION_BUILD=$(echo $(semver 0.1.1 -i prerelease --preid ${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}))" >> $GITHUB_ENV
      - name: Update versionning
        run: |
          git config --global user.email "mickael.djegherif@outlook.fr"
          git config --global user.name "Mike"
          npm version ${{env.GITHUB_VERSION_BUILD}}
          echo ${{env.GITHUB_VERSION_BUILD}} >> README.md
          git commit -a -m "new version ${{env.GITHUB_VERSION_BUILD}}"
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_SECRET }}
          slug: SignSpeakOrganization/FRONT

      - name: Generate jsdoc
        run: npm run jsdoc
      
      
          
